
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
      生成启动时间为 10/29/2023 10:38:09 PM。
      
      节点 1 上的项目“E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\3.28.0-rc2\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        D:\\VS2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        D:\\VS2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\3.28.0-rc2\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=D:\\VS2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\3.28.0-rc2\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.28
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/3.28.0-rc2/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
      生成启动时间为 10/29/2023 10:38:11 PM。
      
      节点 1 上的项目“E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\3.28.0-rc2\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        D:\\VS2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\VS2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\3.28.0-rc2\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\VS2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\3.28.0-rc2\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.10
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/3.28.0-rc2/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/CMakeScratch/TryCompile-6jsfpa"
      binary: "E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/CMakeScratch/TryCompile-6jsfpa"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/CMakeScratch/TryCompile-6jsfpa'
        
        Run Build Command(s): D:/VS2022/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_3fcb1.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
        生成启动时间为 10/29/2023 10:38:12 PM。
        
        节点 1 上的项目“E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\CMakeScratch\\TryCompile-6jsfpa\\cmTC_3fcb1.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_3fcb1.dir\\Debug\\”。
          正在创建目录“E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\CMakeScratch\\TryCompile-6jsfpa\\Debug\\”。
          正在创建目录“cmTC_3fcb1.dir\\Debug\\cmTC_3fcb1.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_3fcb1.dir\\Debug\\cmTC_3fcb1.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_3fcb1.dir\\Debug\\cmTC_3fcb1.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          D:\\VS2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3fcb1.dir\\Debug\\\\" /Fd"cmTC_3fcb1.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "D:\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.37.32825 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3fcb1.dir\\Debug\\\\" /Fd"cmTC_3fcb1.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "D:\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          D:\\VS2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\CMakeScratch\\TryCompile-6jsfpa\\Debug\\cmTC_3fcb1.exe" /INCREMENTAL /ILK:"cmTC_3fcb1.dir\\Debug\\cmTC_3fcb1.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/CMakeScratch/TryCompile-6jsfpa/Debug/cmTC_3fcb1.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/CMakeScratch/TryCompile-6jsfpa/Debug/cmTC_3fcb1.lib" /MACHINE:X64  /machine:x64 cmTC_3fcb1.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_3fcb1.vcxproj -> E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\CMakeScratch\\TryCompile-6jsfpa\\Debug\\cmTC_3fcb1.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_3fcb1.dir\\Debug\\cmTC_3fcb1.tlog\\unsuccessfulbuild”。
          正在对“cmTC_3fcb1.dir\\Debug\\cmTC_3fcb1.tlog\\cmTC_3fcb1.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\CMakeScratch\\TryCompile-6jsfpa\\cmTC_3fcb1.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.09
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/CMakeScratch/TryCompile-cpa5c5"
      binary: "E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/CMakeScratch/TryCompile-cpa5c5"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/CMakeScratch/TryCompile-cpa5c5'
        
        Run Build Command(s): D:/VS2022/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_e85e6.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
        生成启动时间为 10/29/2023 10:38:14 PM。
        
        节点 1 上的项目“E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\CMakeScratch\\TryCompile-cpa5c5\\cmTC_e85e6.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_e85e6.dir\\Debug\\”。
          正在创建目录“E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\CMakeScratch\\TryCompile-cpa5c5\\Debug\\”。
          正在创建目录“cmTC_e85e6.dir\\Debug\\cmTC_e85e6.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_e85e6.dir\\Debug\\cmTC_e85e6.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_e85e6.dir\\Debug\\cmTC_e85e6.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          D:\\VS2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_e85e6.dir\\Debug\\\\" /Fd"cmTC_e85e6.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "D:\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.37.32825 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_e85e6.dir\\Debug\\\\" /Fd"cmTC_e85e6.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "D:\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          D:\\VS2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\CMakeScratch\\TryCompile-cpa5c5\\Debug\\cmTC_e85e6.exe" /INCREMENTAL /ILK:"cmTC_e85e6.dir\\Debug\\cmTC_e85e6.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/CMakeScratch/TryCompile-cpa5c5/Debug/cmTC_e85e6.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/CMakeP/CppCmake/P2_static_and_dynamic_libraries/CMakeFiles/CMakeScratch/TryCompile-cpa5c5/Debug/cmTC_e85e6.lib" /MACHINE:X64  /machine:x64 cmTC_e85e6.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_e85e6.vcxproj -> E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\CMakeScratch\\TryCompile-cpa5c5\\Debug\\cmTC_e85e6.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_e85e6.dir\\Debug\\cmTC_e85e6.tlog\\unsuccessfulbuild”。
          正在对“cmTC_e85e6.dir\\Debug\\cmTC_e85e6.tlog\\cmTC_e85e6.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\CMakeP\\CppCmake\\P2_static_and_dynamic_libraries\\CMakeFiles\\CMakeScratch\\TryCompile-cpa5c5\\cmTC_e85e6.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.07
        
      exitCode: 0
...
